### ISSUE TITLE
couldn't find "libavutil.so"

### ISSUE THREAD

**Issue by tchiloh** [martijn00/FFmpegMediaMetadataRetrieverXamarin#1]
Your sample is working, but when I use it in my project then I get exception when I initialize new variable (FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();). The exception:

Java.Lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/*****_/base.apk"],nativeLibraryDirectories=[/data/app/**_**_/lib/arm64, /data/app/**_***/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libavutil.so"

**Comment by tchiloh** [comment]
I get this error on OnePlus 3 and not on HTC One M8

**Comment by Purvik** [comment]
@tchiloh Did you solve this issue? We're having same for OnePlus or you can say arm64-v8a architecture devices. Any help will be appreciated.

**Comment by martijn00** [comment]
Update is online now.
